### ISSUE TITLE
Commit standards

### ISSUE THREAD

**Issue by jpkelly095** [chrisdaly3/chiclets#1]
These commit subjects/messages do not conform to good commit standards. In the future please ensure all commits conform to the following standards:

- Commit messages must have a subject line and may have body copy. These must be separated by a blank line.
- The subject line must not exceed 50 characters
- The subject line should be capitalized and must not end in a period
- The subject line must be written in imperative mood (Fix, not Fixed / Fixes etc.)
- The body copy must be wrapped at 72 columns
- The body copy must only contain explanations as to what and why, never how. The latter belongs in documentation and implementation.

**Comment by chrisdaly3** [comment]
Thank you for your suggestions. Closed without further consideration.
